version: '3.8'

services:
  # Frontend development server
  frontend:
    build:
      context: .
      target: dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm run dev:frontend

  # Backend API server
  backend:
    build:
      context: .
      target: dev
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - local-data:/data
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - PROVIDER_TYPE=${PROVIDER_TYPE:-local}
      - API_PORT=8000
      - REALTIME_PORT=8001
      - JWT_SECRET=${JWT_SECRET}
      - LOCAL_DATA_PATH=/data
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-loveclaudecode}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    command: npm run dev:backend

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-loveclaudecode}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LocalStack for AWS services (development)
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,dynamodb,lambda,cognito,appsync,secretsmanager
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - aws

  # Firebase Emulator Suite
  firebase-emulator:
    image: andreysenov/firebase-tools:latest
    ports:
      - "9099:9099"   # Auth
      - "8080:8080"   # Firestore
      - "9199:9199"   # Storage
      - "5001:5001"   # Functions
      - "4000:4000"   # Emulator UI
    volumes:
      - firebase-data:/opt/firebase/data
      - ./firebase.json:/opt/firebase/firebase.json:ro
    command: firebase emulators:start --only auth,firestore,storage,functions --project demo-project
    profiles:
      - firebase

  # Adminer for database management (development only)
  adminer:
    image: adminer:latest
    ports:
      - "8090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    profiles:
      - tools

  # Nginx reverse proxy (optional, for production-like setup)
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:
  localstack_data:
  local-data:
  firebase-data:

networks:
  default:
    name: loveclaudecode
    driver: bridge