global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Backend metrics
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL exporter (if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # LocalStack metrics
  - job_name: 'localstack'
    static_configs:
      - targets: ['localstack:4566']
    metrics_path: '/_localstack/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']